<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Repositories\Vacancy\Implementations\.gitkeep" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.30">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.30">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Athuentication\" />
    <Folder Include="Controllers\Admin\" />
    <Folder Include="Controllers\Jobseeker\" />
    <Folder Include="Controllers\Application\" />
    <Folder Include="Controllers\Matching\" />
    <Folder Include="Controllers\Contact\" />
    <Folder Include="Controllers\Notification\" />
    <Folder Include="DTOs\Authentication\" />
    <Folder Include="DTOs\Admin\" />
    <Folder Include="DTOs\Jobseeker\" />
    <Folder Include="DTOs\Application\" />
    <Folder Include="DTOs\Matching\" />
    <Folder Include="DTOs\Contact\" />
    <Folder Include="DTOs\Notification\" />
    <Folder Include="Data\" />
    <Folder Include="Models\JobSeeker\" />
    <Folder Include="Models\Application\" />
    <Folder Include="Models\Contact\" />
    <Folder Include="Models\Notication\" />
    <Folder Include="Models\User\" />
    <Folder Include="Repositories\Jobseeker\" />
    <Folder Include="Repositories\Employer\" />
    <Folder Include="Repositories\Application\" />
    <Folder Include="Repositories\ContactRequest\" />
    <Folder Include="Repositories\Notification\" />
    <Folder Include="Repositories\User\" />
    <Folder Include="Services\Matching\" />
    <Folder Include="Services\Jobseeker\" />
    <Folder Include="Services\Employer\" />
    <Folder Include="Services\Contact\" />
    <Folder Include="Services\Authentication\" />
    <Folder Include="Services\Admin\" />
    <Folder Include="Services\Application\" />
    <Folder Include="Services\Notification\" />
    <Folder Include="Storage\" />
  </ItemGroup>

</Project>
